### ISSUE TITLE
MPV Support and Explaination

### ISSUE THREAD

**Issue by smhmd** [giuseppe-dandrea/Stream-to-VLC#3]
Could you consider providing support for [mpv](https://github.com/mpv-player/mpv)?
Could you, also, provide an explanation of how the script works? what's the end-result sent to `xdg-open`?

**Comment by giuseppe-dandrea** [comment]
Hi, I'm not going to support other players, but you are free to fork this and implement on your own.

This script extract the media source from the streaming page and send it to the player through the `vlcs` custom protocol.

If you're using Windows change the last two lines of `vlc_stream.bat` starting your player instead of VLC and using `%argp%` as the url of the video.

If you're on Linux change the `TryExec` line in `vlc-stream.desktop` with the path of your player and then change `vlc-stream.sh` replacing the calls to `vlc` with your player using `${arg:5}` as the url of the video.
